### ISSUE TITLE
Ready the repository

### ISSUE THREAD

**Issue by katyhuff** [arfc/cyder#16]
Assume upstream is ARFC and origin is gwenchee fork.

- [ ] `git checkout develop && git checkout -b cyder0.1 && git push origin cyder0.1 && git push upstream cyder0.1`
- [ ]  `git checkout develop && git checkout -b removal && git rm -rf src input output *.py && git commit -am "removes src, input, and output from develop` 
- [ ] edit the License to be a current, BSD3 license to ARFC or ARFC and authors, with author list"
- [ ] edit the readme to delete anything not relevant to new cyder. Add a line pointing to https://github.com/arfc/cyder/releases/tag/v0.1
- [ ] `git commit -am "adds updates to license and readme" && git push origin removal`
- [ ] make a PR to develop from gwenchee removal branch

**Comment by gwenchee** [comment]
Closed with https://github.com/arfc/cyder/pull/19
