### ISSUE TITLE
Bidding/ Material Exchange Editing

### ISSUE THREAD

**Issue by jbae11** [arfc/cyder#2]
Can you recommend me a way to go about editing the bidding/material exchange part of the code?

currently it seems 'makerequest' and 'addresource' are the two functions that should be replaced.

Let me know what you think.

**Comment by katyhuff** [comment]
Yes, makeRequest and addResource are the two functions that need to be replaced. Can you make your question more specific?

**Comment by katyhuff** [comment]
closing because this was never clear / question never answered. Feel free to reopen @jbae11 .
