### ISSUE TITLE
handleTick(time) -> Tick() and handleTock(time) -> Tock()

### ISSUE THREAD

**Issue by katyhuff** [arfc/cyder#3]
Not passing the time variable through the tick and tock is going to cause some drama later where these tick and tock functions use the time variable in implementation..

For example, the Tick function uses the time variable like so:

```
if (time==0){
```

and then also when it passes time to the make requests variable.

```
makeRequests(time)
```

This issue can be closed when the dependency chain is resolved such that Tick() and Tock() successfully execute without using the time variable as passed through the function. This will probably be handled with the time funtionality in the ctx()

Related: Double check how the parameter "the_time" is used in the nuclide transport context. If it is a different solution, create a new issue. 

This was noted in PR #1  and will be handled by @jbae11 .

**Comment by jbae11** [comment]
@katyhuff 
Please do correct me if I'm totally lost, but

it seems like the ctx is a pointer that points to

simulation-wide variables (like time), just like a global variable, but somehow better.

In other archetypes, the time variable is expressed in

`ctx->time()`
or
`context()->time()`

Would it be extremely naive to believe that the current 'time' variable
can simply be substituted with 'context()->time' ?

**Comment by katyhuff** [comment]
Yep. That's exactly what I was trying to say above "This will probably be handled with the time funtionality in the ctx()". Sorry that wasn't clear.

**Comment by jbae11** [comment]
PR #5 addresses this issue.
