### ISSUE TITLE
Cloning?

### ISSUE THREAD

**Issue by jbae11** [arfc/cyder#4]
@katyhuff 

If I am not mistaken,
the "cloneModuleMembersFrom" and "copyFreshModel" functions

can be replaced by the following?

`#pragma cyclus clone cyder::cyder`

All the other facilities replace their clone functions with either
`#pragma cyclus clone`
or
`#pragma cyclus clone cyacmore::[facilityname]`

I'm sure it is more complicated than this, though.

**Comment by katyhuff** [comment]
Yes, it really is that simple.

**Comment by katyhuff** [comment]
Which is to say, let us together celebrate the power and mystery of code generation. 

![bitmoji](https://render.bitstrips.com/v2/cpanel/10152648-116454032_15-s1-v1.png?transparent=1&palette=1&width=246)
