### ISSUE TITLE
startOpYear / startOpMonth

### ISSUE THREAD

**Issue by jbae11** [arfc/cyder#7]
would this sit well with DeployInst or when it is deployed by other institutions?'

**Comment by katyhuff** [comment]
These things are now handled by the institution (and/or Region) explicitly.

**Comment by jbae11** [comment]
so there is no need for the input file to contain those parameters? or should I just leave them?

**Comment by katyhuff** [comment]
I'm tempted to use the Socratic method here: What do you think? How would you find out?

However, I'll just state the answer. They should be removed and any internal-to-Cyder references to them should be removed/handled cleanly. I don't think there are any references to them in Cyder, but you should check (recall grep). Anyway, these variables were once part of the parameters inherited from the FacilityModel. So, all facilities were initialized with them. Now, instead, it's all handled in the Agent class. There is a notion of the EnterTime that is handled with your pragmas instead.

**Comment by jbae11** [comment]
I guess I would find out by first searching what it does and how it affects deployment in the bigger realm of cyclus? and if the newer cyder .h files have them or not. But I suppose there would be a more technical approach to this. 

#8
